# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' EstNull
#' This function is a Rcpp version of Wenguang Sun and Tony T. Cai's
#' EstNull.func R function, estimating null distribution from data.
#' Sun, W., & Cai, T. T. (2007). Oracle and Adaptive Compound Decision
#' Rules for False Discovery Rate Control.
#' Journal of the American Statistical Association,
#' 102(479), 901–912.
#' @author Qi Gao
#' @param x Input vector of all coexpression values
#' @param gamma Parameter setting the stopping threshold
#' @return List of mean and std
#' @export
EstNull_cpp <- function(x, gamma = 0.1) {
    .Call('_BLightning_EstNull_cpp', PACKAGE = 'BLightning', x, gamma)
}

#' cal_coexp
#' This function calculates the coexpression patterns between genes
#' and returns the coexpression matrix.
#' @author Qi Gao
#' @param X Input binarized cell (row) by gene (column) matrix
#' @return Coexpression matrix
#' @export
coexp_arma <- function(X) {
    .Call('_BLightning_coexp_arma', PACKAGE = 'BLightning', X)
}

